// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=src/external/repo/implementations/sea_query_postgres/migrations");
}
